In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
matrix = np.array(my_matrix)

In [9]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(9)

array([0.42951743, 0.92364081, 0.69970788, 0.99911889, 0.28770025,
       0.0842042 , 0.12925451, 0.11546179, 0.22523724])

In [17]:
arr = np.random.randint(1,100,10)

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
rnarr = np.random.randint(0,50,10)

In [22]:
arr.max()

24

In [23]:
arr.min()

0

In [24]:
arr.argmax()

24

In [25]:
rnarr.max()

49

In [26]:
rnarr.min()

10

In [27]:
rnarr

array([25, 42, 38, 16, 10, 44, 45, 49, 35, 26])

In [28]:
rnarr.argmax()

7

In [29]:
rnarr.argmin()

4

In [30]:
rnarr.shape

(10,)

In [31]:
rnarr.dtype

dtype('int32')

###### Numpy indexing nd selection

In [32]:
import numpy as np

In [33]:
ar = np.arange(0,11)

In [34]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
ar[9]

9

In [36]:
ar[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [41]:
ar[0:5] = 1

In [42]:
ar

array([ 1,  1,  1,  1,  1,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_array = ar[0:5]

In [55]:
slice_of_array

array([10,  0,  0,  0,  0])

In [56]:
slice_of_array[1:] = 0

In [57]:
ar

array([10,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [58]:
arr_copy = ar.copy()

In [59]:
ar

array([10,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [62]:
arr_copy[:] = 1

In [63]:
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [73]:
ar

array([10,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

###### PANDAS

In [1]:
import numpy as np
import pandas as pd


In [4]:
labels = ['a','b','c']
my_data=[10,20,30]
ar = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [28]:
pd.Series(data=[1,2,3,4,5,6] )

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [19]:
ser1 = pd.Series([1,2,3,4],['India','USA','Japan','USSR'])

In [20]:
ser1

India    1
USA      2
Japan    3
USSR     4
dtype: int64

In [21]:
ser2 = pd.Series([1,2,5,4],['India','USA','UAE','USSR'])

In [22]:
ser2

India    1
USA      2
UAE      5
USSR     4
dtype: int64

In [23]:
 ser1+ser2

India    2.0
Japan    NaN
UAE      NaN
USA      4.0
USSR     8.0
dtype: float64

In [24]:
ser1*ser2

India     1.0
Japan     NaN
UAE       NaN
USA       4.0
USSR     16.0
dtype: float64

In [26]:
ser1['USA']

2

In [29]:
import numpy as np 
import pandas as pd
from numpy.random import randn

In [30]:
np.random.seed(101)

In [31]:
df = pd.DataFramew

AttributeError: module 'pandas' has no attribute 'DataFramew'

In [39]:
x = 1_000_000_000
y = 100_000
total = x+y

In [40]:
print(f'{total:,}')

1,000,100,000
